const emailMessageTypes = {
  MESSAGE: 'MESSAGE',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  SUBSCRIBER: 'SUBSCRIBER',
  VOLUNTARY: 'VOLUNTARY',
  VOLUNTARY_ACCEPTED: 'VOLUNTARY_ACCEPTED'
};
export default emailMessageTypes;
