const EMAIL_MESSAGE_TYPES = {
  MESSAGE: 'MESSAGE',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  SUBSCRIBER: 'SUBSCRIBER',
  VOLUNTARY: 'VOLUNTARY'
};
export default EMAIL_MESSAGE_TYPES;
